// ─────────────────────────────────────────────────────────────────────────
// Operaciones sobre un repositorio de Bitbucket
//
// Cada funcion hace UNA cosa y devuelve si resulto. El orden en que se
// llaman y que hacer si alguna falla lo decide full_run.rs.
// ─────────────────────────────────────────────────────────────────────────

use serde_json::json;

use super::super::eks::config::RefreshError;
use super::client::{mensaje_error, url_repo, BBClient};

// Contenido estandar del banco para el commit inicial. Trasladado textual
// desde la herramienta anterior, donde fue confirmado contra un repositorio
// real. No modificar sin confirmar el estandar vigente con el equipo.
const GITIGNORE: &str = r#"# These are some examples of commonly ignored file patterns.
# You should customize this list as applicable to your project.
# Learn more about .gitignore:
#     https://www.atlassian.com/git/tutorials/saving-changes/gitignore

# Node artifact files
node_modules/
dist/

# Compiled Java class files
*.class

# Compiled Python bytecode
*.py[cod]

# Log files
*.log

# Package files
*.jar

# Maven
target/
dist/

# JetBrains IDE
.idea/

# Unit test reports
TEST*.xml

# Generated by MacOS
.DS_Store

# Generated by Windows
Thumbs.db

# Applications
*.app
*.exe
*.war

# Large media files
*.mp4
*.tiff
*.avi
*.flv
*.mov
*.wmv
"#;

const README: &str = r#"# README
This README would normally document whatever steps are necessary to get your application up and running.

## What is this repository for?

* Quick summary
* Version
* [Learn Markdown](https://bitbucket.org/tutorials/markdowndemo)

## How do I get set up?

* Summary of set up
* Configuration
* Dependencies
* Database configuration
* How to run tests
* Deployment instructions

## Contribution guidelines

* Writing tests
* Code review
* Other guidelines

## Who do I talk to?

* Repo owner or admin
* Other community or team contact
"#;

// Resultado de verificar si un repositorio ya esta creado.
pub enum EstadoRepo {
    NoExiste,
    Existe(String),  // URL del repo que ya estaba
    ErrorAlVerificar(String),
}

pub async fn verificar(
    client: &BBClient,
    workspace: &str,
    repo: &str,
) -> Result<EstadoRepo, RefreshError> {
    let (codigo, cuerpo) = client.get(&format!("/repositories/{}/{}", workspace, repo)).await?;

    Ok(match codigo {
        // 404 es la respuesta buena: el nombre esta libre.
        404 => EstadoRepo::NoExiste,
        200 => EstadoRepo::Existe(url_repo(&cuerpo).unwrap_or_else(|| "—".to_string())),
        otro => EstadoRepo::ErrorAlVerificar(format!("HTTP {}: {}", otro, mensaje_error(&cuerpo))),
    })
}

// Configuracion estandar del equipo: privado, sin forks, sin issues ni wiki,
// rama principal master. Misma que usaba la herramienta anterior.
pub async fn crear(
    client: &BBClient,
    workspace: &str,
    repo: &str,
    project_key: &str,
) -> Result<String, RefreshError> {
    let payload = json!({
        "scm": "git",
        "is_private": true,
        "project": { "key": project_key },
        "mainbranch": { "name": "master", "type": "branch" },
        "fork_policy": "no_forks",
        "has_issues": false,
        "has_wiki": false,
    });

    let (codigo, cuerpo) = client
        .post_json(&format!("/repositories/{}/{}", workspace, repo), payload)
        .await?;

    if codigo == 200 || codigo == 201 {
        return Ok(url_repo(&cuerpo).unwrap_or_else(|| {
            format!("https://bitbucket.org/{}/{}", workspace, repo)
        }));
    }

    // Caso frecuente y con causa concreta: vale la pena nombrarlo en vez de
    // devolver un 403 pelado que no dice como arreglarlo.
    if cuerpo.contains("admin:repository") {
        return Err(RefreshError::new(
            "crear_repositorio",
            "Sin permisos para crear repositorios. El token necesita el scope admin:repository:bitbucket.",
        ));
    }

    Err(RefreshError::new(
        "crear_repositorio",
        format!("HTTP {}: {}", codigo, mensaje_error(&cuerpo)),
    ))
}

// Commit inicial con .gitignore y README.md.
//
// NO es opcional: Bitbucket no permite crear ramas en un repositorio vacio
// porque no hay nada desde donde ramificar. Este commit es lo que hace
// existir a master de verdad.
pub async fn commit_inicial(
    client: &BBClient,
    workspace: &str,
    repo: &str,
) -> Result<(), RefreshError> {
    let campos = [
        ("message", "Initial commit"),
        ("branch", "master"),
        (".gitignore", GITIGNORE),
        ("README.md", README),
    ];

    let (codigo, cuerpo) = client
        .post_multipart(&format!("/repositories/{}/{}/src", workspace, repo), &campos)
        .await?;

    if codigo == 200 || codigo == 201 {
        Ok(())
    } else {
        Err(RefreshError::new(
            "commit_inicial",
            format!("HTTP {}: {}", codigo, mensaje_error(&cuerpo)),
        ))
    }
}

// Necesario para poder vincular SonarQube Cloud despues.
pub async fn activar_pipelines(
    client: &BBClient,
    workspace: &str,
    repo: &str,
) -> Result<(), RefreshError> {
    let (codigo, cuerpo) = client
        .put_json(
            &format!("/repositories/{}/{}/pipelines_config", workspace, repo),
            json!({ "enabled": true }),
        )
        .await?;

    if codigo == 200 || codigo == 201 {
        Ok(())
    } else {
        Err(RefreshError::new(
            "activar_pipelines",
            format!(
                "HTTP {}: {} — activar manualmente en Repositorio → Settings → Pipelines",
                codigo,
                mensaje_error(&cuerpo)
            ),
        ))
    }
}

// Crea una rama desde master. Devuelve Ok tambien cuando la rama ya existia:
// el estado final es el deseado, que es lo que importa.
pub async fn crear_rama(
    client: &BBClient,
    workspace: &str,
    repo: &str,
    rama: &str,
) -> Result<(), RefreshError> {
    let (codigo, cuerpo) = client
        .post_json(
            &format!("/repositories/{}/{}/refs/branches", workspace, repo),
            json!({ "name": rama, "target": { "hash": "master" } }),
        )
        .await?;

    match codigo {
        200 | 201 | 409 => Ok(()),
        otro => Err(RefreshError::new(
            "crear_rama",
            format!("'{}' HTTP {}: {}", rama, otro, mensaje_error(&cuerpo)),
        )),
    }
}

// Chile usa "development" (con T) y Peru usa "develop" (sin T). Es un error
// frecuente al hacerlo a mano, por eso la regla vive en un solo lugar en vez
// de que la interfaz mande el nombre ya resuelto.
pub fn rama_desarrollo(pais: &str) -> &'static str {
    match pais.to_uppercase().as_str() {
        "PE" => "develop",
        _ => "development",
    }
}
